"""AppImage 更新信息 + `.zsync` —— 交付的两件产物，以及它们的每一步都真的有工具可按。

来源（rant 2026-09-30T11:42:41 → issue #1934/Part 2/2，Part 1/2 = #1781）：AppImage 官方
目录的自动检查对 `AppImage/appimage.github.io#6453` 点名两条，第一条是名字里的 `linux`
（已修），第二条是**这一条**：

    The AppImage contains no update information, so users cannot update it with
    AppImageUpdate or similar tools. Please consider embedding it when building the
    AppImage (e.g., appimagetool -u) and publishing the .zsync file next to the AppImage

`packaging/make-installer.sh` 收集的 AppImage 来自 electron-builder，而它用的是自己的更新
方案 —— 上游文档的原话是「AppImages generated by electron-builder cannot be updated using
the usual tools」，`app-builder-lib` 的 AppImageTarget 也没有任何 update-info 参数。上游对
electron-builder 给出的唯一那条路是：用 AppImage 自己的 `--appimage-extract` 解成 AppDir，
再用 `appimagetool -u` 重新封装。

为什么本文件执行而不是读文本
----------------------------
这条 requirement 的失败形态是**静默**的：`appimagetool -u` 内嵌更新信息，而 `.zsync` 只有
在 `zsyncmake` 在场时才会被生成（`appimagetool --help`: "-u ... if zsyncmake is installed,
generate zsync file"）。也就是说，一个「装了 appimagetool 却没装 zsyncmake」的环境会安静地
发布一个**仍然不可更新**的 AppImage，而流水线全绿 —— 那正是这条 rant 要修的那个状态。
所以本文件的断言落在**执行结果**上：

* `packaging/make-appimage-updatable.sh` 被真的跑起来（工具用替身：`appimagetool` 记下它
  收到的更新信息串并产出两件文件，`zsyncmake` / `mksquashfs` 只是存在），断言的是
  `dist/artifacts/` 里真的多出了 `<name>` 与 `<name>.zsync`；
* 缺工具那一侧同样被执行：从 PATH 里拿走 `appimagetool`（再拿走 `zsyncmake`）后脚本必须
  **非零退出并点名缺的是哪个** —— 一个「缺工具就跳过」的实现会在这里被抓住；
* workflow 的两处接线由**它自己的 YAML** 断言：Linux 腿装齐两件工具、上传清单里有 `*.zsync`。

命名与更新信息串的**关系**也在这里钉住：产物名里那一段架构、以及更新信息串里 `.zsync` 的
通配形态，都取自同一个 `ARCH`，所以「脚本产出的名字」与「内嵌的更新信息指向的名字」不可能
各自漂移。
"""

from __future__ import annotations

import fnmatch
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
INSTALLER = REPO_ROOT / "packaging" / "make-installer.sh"
UPDATABLE = REPO_ROOT / "packaging" / "make-appimage-updatable.sh"
WORKFLOW = REPO_ROOT / ".github" / "workflows" / "build-release.yml"

VERSION = "9.9.9"
ARCH = "x86_64"
REPO_SLUG = "argszero/emrg"
#: 一个**不是**本仓库的 slug。对象的输入与断言的期望值都从被注入的那个 slug 派生，
#: 所以「读 `GITHUB_REPOSITORY`」与「写死本仓库的 owner/repo」在这一行上必然产出不同的
#: 串 —— 而用本仓库的 slug 驱动时两者逐字节相同，任何变异臂都杀不掉（实测于 #1938）。
FORK_SLUG = "someone-else/emrg-fork"
OUT_NAME = f"EMRG-{VERSION}-{ARCH}.AppImage"


def _expected_update_info(slug: str) -> str:
    """按被注入的 slug 派生期望串。

    期望值不得写死成某一个 slug：写死了，同一个陷阱就在上一层重建 —— 断言与对象一起
    吃同一个字面量，仍然分不出「读进来的」与「写死的」。
    """
    owner, _, repo = slug.partition("/")
    return f"gh-releases-zsync|{owner}|{repo}|latest|EMRG-*-{ARCH}.AppImage.zsync"


#: AppImageSpec 的 `gh-releases-zsync` 形态（draft.md#github-releases）：
#: 传输方式 | GitHub 用户/组织 | 仓库 | release tag | `.zsync` 的文件名（`*` 为规范允许的通配）
EXPECTED_UPDATE_INFO = _expected_update_info(REPO_SLUG)


# ── 替身 ────────────────────────────────────────────────────────────────────


_STUB_APPIMAGETOOL = """\
#!/bin/sh
# 替身 appimagetool：记下收到的更新信息串与各位置参数，并产出两件文件。
# 真实工具把「内嵌」与「生成 .zsync」做成同一次封装的两个产物，替身照此形态。
set -eu
info=""
out=""
srcdir=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    -u|--updateinformation) info="$2"; shift 2 ;;
    -n|--no-appstream) shift ;;
    *) srcdir="$out"; out="$1"; shift ;;
  esac
done
printf '%s\\n' "$info" > "$STUB_LOG/update-info"
printf '%s\\n' "$out" > "$STUB_LOG/out-name"
printf '%s\\n' "$srcdir" > "$STUB_LOG/source-dir"
printf '%s\\n' "${ARCH:-}" > "$STUB_LOG/arch"
printf 'appimage payload\\n' > "$out"
printf 'zsync: 0.6.2\\nFilename: %s\\n' "$out" > "$out.zsync"
"""

_STUB_NOOP = "#!/bin/sh\nexit 0\n"

#: 脚本自己是 bash + coreutils，不只是三件打包工具。它们被**链接进替身目录**，于是这一步的
#: PATH 可以是**封闭的**，只有它自己造的东西。
#:
#: 为什么必须封闭：把宿主的 `/usr/bin` 留在 PATH 上，「缺工具」那一侧就成了一句空话 ——
#: ubuntu 腿装了 `zsync` 与 `squashfs-tools`，那些工具在 /usr/bin 里躺着，替身目录里拿掉
#: 一份并不等于它不在 PATH 上。实测 2026-10-08（run 37763045245，PR #1938）：同一份测试在
#: macOS 全绿，在 ubuntu 腿
#: `test_a_missing_tool_fails_and_names_it[zsyncmake]` / `[mksquashfs]` 双双变红 —— 红的
#: 是这条测试的模拟，不是脚本（脚本按规矩用了它找得到的工具，并以 0 退出）。
#: 缺少的名字会以「命令找不到」的形式当场变红，而不是安静地少测一侧。
_COREUTILS = (
    "sh", "bash", "mkdir", "mktemp", "cp", "chmod", "rm", "grep", "wc", "tr",
    "basename", "uname", "dirname", "sed", "cat", "find",
)


def _write_exe(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8")
    path.chmod(0o755)


def _stub_bin(tmp_path: Path, *, tools: tuple[str, ...] = ("appimagetool", "zsyncmake", "mksquashfs")) -> tuple[Path, Path]:
    """工具替身目录 + 它们写日志的目录。这个目录就是这一步的**全部** PATH。"""
    bin_dir = tmp_path / "bin"
    log_dir = tmp_path / "stublog"
    bin_dir.mkdir(parents=True, exist_ok=True)
    log_dir.mkdir(parents=True, exist_ok=True)
    for name in _COREUTILS:
        real = shutil.which(name)
        if real is not None:
            (bin_dir / name).symlink_to(real)
    for tool in tools:
        _write_exe(bin_dir / tool, _STUB_APPIMAGETOOL if tool == "appimagetool" else _STUB_NOOP)
    return bin_dir, log_dir


def _fake_source(tmp_path: Path) -> Path:
    """一个能被 `--appimage-extract` 解出 AppDir 的假 AppImage。"""
    src = tmp_path / "emrg-gui-dist" / f"EMRG-{VERSION}.AppImage"
    src.parent.mkdir(parents=True, exist_ok=True)
    _write_exe(
        src,
        "#!/bin/sh\n"
        "# 替身 AppImage：只实现被测脚本用到的那一个开关。\n"
        'set -eu\n'
        'for a in "$@"; do [ "$a" = "--appimage-extract" ] || continue; mkdir -p squashfs-root; exit 0; done\n'
        "exit 1\n",
    )
    return src


def _run_updatable(
    tmp_path: Path, *, tools: tuple[str, ...], slug: str | None = REPO_SLUG
) -> tuple[subprocess.CompletedProcess, Path, Path]:
    """执行 `make-appimage-updatable.sh`，回 (结果, 输出目录, 替身日志目录)。

    `slug` 是被注入的 `GITHUB_REPOSITORY`；`None` 表示**不设**这个变量，用来驱动
    「变量缺席」那一行。默认值是本仓库的 slug，只是为了让老用例少改一行 —— 断言「串
    是从环境读来的」的用例必须显式换一个 slug，否则它就是被喂了自己要的答案。
    """
    if shutil.which("bash") is None:  # pragma: no cover - POSIX-less host
        pytest.skip("no bash on PATH: this guard drives the script itself, which it cannot run")

    bin_dir, log_dir = _stub_bin(tmp_path, tools=tools)
    src = _fake_source(tmp_path)
    out_dir = tmp_path / "dist" / "artifacts"
    out_dir.mkdir(parents=True, exist_ok=True)

    env = {
        # 只有替身目录：宿主的 /usr/bin 会把「被拿走」的工具还回来（见 `_COREUTILS`）。
        "PATH": str(bin_dir),
        "HOME": str(tmp_path),
        "TMPDIR": str(tmp_path),
        "STUB_LOG": str(log_dir),
        "ARCH": ARCH,
    }
    if slug is not None:
        env["GITHUB_REPOSITORY"] = slug
    result = subprocess.run(
        ["bash", str(UPDATABLE), str(src), str(out_dir), OUT_NAME],
        cwd=str(tmp_path), env=env, capture_output=True, text=True,
        # 脚本的报文是中文（issue #1132）：宿主 locale 的编解码器不是它们的解码器。
        encoding="utf-8", errors="replace", timeout=120,
    )
    return result, out_dir, log_dir


# ── 1. 两件产物 ─────────────────────────────────────────────────────────────


@pytest.mark.skipif(
    sys.platform == "win32",
    reason="bash on the Windows runner is WSL's, not the shell these scripts run under in "
    "CI (the same statement tests/test_a_step_without_its_product_refuses.py makes)",
)
def test_the_step_produces_the_appimage_and_its_zsync(tmp_path):
    """方向一：跑通时必须**两件都在** `dist/artifacts/` 里。

    `.zsync` 单独缺席正是要修的告警，所以这里断言的是集合，不是「脚本没有报错」。
    """
    result, out_dir, _log = _run_updatable(tmp_path, tools=("appimagetool", "zsyncmake", "mksquashfs"))
    assert result.returncode == 0, f"报告失败：{result.stdout}{result.stderr}"

    produced = sorted(p.name for p in out_dir.iterdir())
    assert OUT_NAME in produced, f"没有产出 AppImage：{produced}"
    assert f"{OUT_NAME}.zsync" in produced, (
        f"AppImage 在，`.zsync` 不在（{produced}）—— 这正是 appimage.github.io 检查点名的"
        f"第二条告警：用户仍然无法用 AppImageUpdate 更新它"
    )
    assert (out_dir / f"{OUT_NAME}.zsync").stat().st_size > 0, "`.zsync` 是空文件"


@pytest.mark.skipif(
    sys.platform == "win32",
    reason="bash on the Windows runner is WSL's, not the shell these scripts run under in CI",
)
def test_the_embedded_update_information_names_this_release(tmp_path):
    """内嵌的串必须是 AppImageSpec 的 `gh-releases-zsync` 形态，且指向**本**仓库的 release。

    owner/repo 取自 `GITHUB_REPOSITORY` 而不是写死：fork 出来的实例发布的 `.zsync` 在它
    自己的 release 上，写死会让那些用户的更新指向上游仓库。
    """
    result, _out_dir, log_dir = _run_updatable(tmp_path, tools=("appimagetool", "zsyncmake", "mksquashfs"))
    assert result.returncode == 0, f"报告失败：{result.stdout}{result.stderr}"

    info = (log_dir / "update-info").read_text(encoding="utf-8").strip()
    assert info == EXPECTED_UPDATE_INFO, (
        f"内嵌的更新信息串是 {info!r}，期望 {EXPECTED_UPDATE_INFO!r}；"
        f"形态见 AppImageSpec draft.md#github-releases"
    )
    # 更新信息里那个 `.zsync` 的名字，必须与脚本产出的 `.zsync` 同名 —— 否则用户的更新
    # 工具会去找一个不存在的文件。两处都从同一个 ARCH 来，这里断言它们确实一致。
    assert info.split("|")[-1] == f"{OUT_NAME}.zsync".replace(VERSION, "*"), (
        f"更新信息指向 {info.split('|')[-1]!r}，而产物是 {OUT_NAME}.zsync —— 两处名字漂移了"
    )
    # 重新封装是**从解出来的 AppDir** 出发的（不是对着原 AppImage 原地改），且架构是显式
    # 传下去的：`appimagetool` 靠它挑 runtime。
    assert (log_dir / "source-dir").read_text(encoding="utf-8").strip().endswith("squashfs-root"), (
        "appimagetool 的 SOURCE 不是 --appimage-extract 解出来的 AppDir"
    )
    assert (log_dir / "arch").read_text(encoding="utf-8").strip() == ARCH


@pytest.mark.skipif(
    sys.platform == "win32",
    reason="bash on the Windows runner is WSL's, not the shell these scripts run under in CI",
)
def test_the_update_information_follows_the_repository_it_is_built_from(tmp_path):
    """内嵌的 owner/repo 必须**来自环境**，而不是写死的本仓库。

    上面那条用例（用本仓库 slug 驱动、再断言这个 slug）分不出两件事：当对象吃的 slug
    与期望串里的 slug 是同一个时，「读 `GITHUB_REPOSITORY`」与「写 `argszero|emrg`」
    产出逐字节相同的串 —— 实测过，把脚本里的 `${OWNER}|${REPO_NAME}` 换成字面量
    `argszero|emrg`，整份文件 10/10 全绿（#1938 的评审）。这里用**另一个** slug 驱动，
    于是那种实现必然把这一行变红，而它正是 docstring 承诺的那句话。
    """
    result, _out_dir, log_dir = _run_updatable(
        tmp_path, tools=("appimagetool", "zsyncmake", "mksquashfs"), slug=FORK_SLUG)
    assert result.returncode == 0, f"报告失败：{result.stdout}{result.stderr}"

    info = (log_dir / "update-info").read_text(encoding="utf-8").strip()
    expected = _expected_update_info(FORK_SLUG)
    assert info == expected, (
        f"从 {FORK_SLUG} 构建，内嵌的更新信息串却是 {info!r}（期望 {expected!r}）—— "
        f"写死的 owner/repo 会让 fork 出去的用户被更新到别人的仓库"
    )
    # 更新信息里那个 `.zsync` 的名字仍须与产物同名：换了 slug 不该动文件名那一段。
    assert info.split("|")[-1] == f"{OUT_NAME}.zsync".replace(VERSION, "*")


@pytest.mark.parametrize(
    "slug, why",
    [
        (None, "变量缺席"),
        ("", "空串"),
        ("emrg", "没有 owner/repo 的分隔斜杠"),
        ("/emrg", "owner 为空"),
        ("argszero/", "repo 为空"),
        ("argszero/emrg/extra", "多于一个斜杠"),
    ],
)
@pytest.mark.skipif(
    sys.platform == "win32",
    reason="bash on the Windows runner is WSL's, not the shell these scripts run under in CI",
)
def test_a_slug_that_is_not_owner_repo_is_refused(tmp_path, slug, why):
    """形态不对的 slug 必须在**碰任何工具之前**就失败，且不留下产物。

    这条分支原先没有被任何用例驱动过，所以它可以被删掉而文件仍然全绿 —— 而删掉之后，
    一条 owner 为空的更新信息串会安静地发布出去。`/emrg`、`argszero/` 与 `a/b/c` 三种
    形态原先**通过**了那道守卫（它只看「有没有斜杠」），产物同样是指向不存在仓库的串，
    所以这里的每一行都是被判据本身拦下的，不是被别的东西顺手拦下的。
    """
    result, out_dir, _log = _run_updatable(
        tmp_path, tools=("appimagetool", "zsyncmake", "mksquashfs"), slug=slug)

    assert result.returncode != 0, (
        f"slug={slug!r}（{why}）被接受了：{result.stdout}{result.stderr}"
    )
    combined = result.stdout + result.stderr
    assert "GITHUB_REPOSITORY" in combined, (
        f"失败报文没有点名是哪个变量（{why}）：{combined[:300]!r}"
    )
    assert not list(out_dir.iterdir()), (
        f"失败之后还留下了产物 {sorted(p.name for p in out_dir.iterdir())} —— "
        f"半个产物比没有产物更坏：上传步骤会把它当作成品"
    )


# ── 2. 缺工具即失败，不降级 ─────────────────────────────────────────────────


@pytest.mark.parametrize("missing", ["appimagetool", "zsyncmake", "mksquashfs"])
@pytest.mark.skipif(
    sys.platform == "win32",
    reason="bash on the Windows runner is WSL's, not the shell these scripts run under in CI",
)
def test_a_missing_tool_fails_and_names_it(tmp_path, missing):
    """方向二：工具缺席是**失败**，且报文点名缺的是哪一个。

    `zsyncmake` 缺席尤其重要：真实 `appimagetool` 在这种情况下仍然会内嵌更新信息、只是
    不生成 `.zsync`，所以一个只看 appimagetool 是否存在的实现会安静地留下告警。
    """
    tools = tuple(t for t in ("appimagetool", "zsyncmake", "mksquashfs") if t != missing)
    result, out_dir, _log = _run_updatable(tmp_path, tools=tools)

    assert result.returncode != 0, (
        f"{missing} 不在 PATH 上，脚本却以 0 退出 —— 一个缺了工具就跳过的步骤会把"
        f"'AppImage 里没有更新信息' 这条告警原样留着，而流水线是绿的"
    )
    combined = result.stdout + result.stderr
    assert missing in combined, f"失败报文没有点名 {missing}：{combined[:300]!r}"
    assert not list(out_dir.iterdir()), (
        f"失败之后还留下了产物 {sorted(p.name for p in out_dir.iterdir())} —— "
        f"半个产物比没有产物更坏：上传步骤会把它当作成品"
    )


# ── 3. 接线：安装器真的调用它 ───────────────────────────────────────────────


def _linux_branch() -> str:
    m = re.search(r"^\s*linux\)\n(?P<body>.*?)^\s*;;\s*$", INSTALLER.read_text(encoding="utf-8"), re.S | re.M)
    assert m, f"{INSTALLER.name} 里找不到 `linux)` 分支 —— 本文件的断言对象变了，需重写"
    return m.group("body")


def test_the_installer_calls_the_step_and_does_not_swallow_its_failure():
    """Linux 分支必须**调用**它，且不得用 `|| true` 把失败吞掉。

    断言的是一次调用本身（`packaging/make-appimage-updatable.sh` 被点名），不是一句注释：
    上一轮同类缺陷（memory `structural-guard-must-assert-the-call`）就是守卫断言了调用里
    的关键字，而那次调用早已不再通向任何地方。
    """
    branch = _linux_branch()
    lines = [l.strip() for l in branch.splitlines() if l.strip() and not l.strip().startswith("#")]
    calls = [l for l in lines if "make-appimage-updatable.sh" in l]
    assert calls, (
        f"{INSTALLER.name} 的 linux 分支没有调用 packaging/make-appimage-updatable.sh —— "
        f"收集完 AppImage 就结束，等于发布一个不含更新信息的 AppImage（rant 2026-09-30T11:42:41）"
    )
    assert not any("|| true" in l for l in calls), (
        f"调用被 `|| true` 吞掉了失败：{calls} —— 步骤缺席与步骤失败在这里必须是同一件事"
    )


# ── 4. workflow：工具与资产清单 ─────────────────────────────────────────────


def _build_steps() -> list[dict]:
    return yaml.safe_load(WORKFLOW.read_text(encoding="utf-8"))["jobs"]["build"]["steps"]


def _linux_tooling_step() -> dict:
    named = [s for s in _build_steps() if s.get("name") == "AppImage update tooling (Linux only)"]
    assert len(named) == 1, (
        f"build-release.yml 里没有唯一的 'AppImage update tooling (Linux only)' 步骤："
        f"{[s.get('name') for s in _build_steps()]}"
    )
    return named[0]


def test_the_linux_leg_installs_both_tools_the_step_needs():
    """`appimagetool` 内嵌更新信息，`zsyncmake` 才会写出 `.zsync` —— 两件都得装。

    只装前者是本条最可能的静默失败形态（见文件头），所以这里逐个点名。
    """
    step = _linux_tooling_step()
    assert step.get("if") == "runner.os == 'Linux'", (
        f"这条步骤只对 Linux 腿有意义，它的 if 是 {step.get('if')!r}"
    )
    run = step["run"]
    for token in ("zsync", "squashfs-tools"):
        assert token in run, f"Linux 腿没有安装 {token}：{run[:400]!r}"
    assert "appimagetool/releases/download/continuous" in run, (
        f"Linux 腿没有取到 appimagetool：{run[:400]!r}"
    )
    assert "APPIMAGE_EXTRACT_AND_RUN=1 appimagetool --version" in run, (
        "取到 appimagetool 之后没有**验证它真的能跑**——CI 里没有 FUSE，不就地解出来跑"
        "的话，这条安装步骤会把一个跑不起来的二进制报告成装好了"
    )


def _upload_paths() -> list[str]:
    steps = [s for s in _build_steps() if "upload-artifact" in str(s.get("uses", ""))]
    assert steps, "build-release.yml 里找不到 actions/upload-artifact 步骤"
    paths = steps[0]["with"]["path"]
    assert isinstance(paths, str) and paths.strip(), f"上传清单不是一段文本：{paths!r}"
    return [l.strip() for l in paths.splitlines() if l.strip()]


def test_the_upload_list_carries_the_zsync():
    """`.zsync` 是一条**发布资产**：`actions/upload-artifact` 的 path 列表是白名单式的，
    没列进去的文件到不了 release，而 release 步骤用的是 `artifacts/*`（描述符跟着走）。

    断言用 `fnmatch` 对一个真实的 `.zsync` 名字，而不是找字面量 `*.zsync`：列表写成
    `dist/artifacts/EMRG-*.zsync` 之类的等价形态也必须算通过。
    """
    paths = _upload_paths()
    name = f"{OUT_NAME}.zsync"
    matched = [p for p in paths if fnmatch.fnmatch(f"dist/artifacts/{name}", p)]
    assert matched, (
        f"上传清单里没有任何一行会带上 {name}：{paths} —— AppImage 会进 release，它旁边的"
        f"`.zsync` 不会，用户的更新工具因此找不到它"
    )


def test_the_release_step_publishes_every_uploaded_asset():
    """上游那一步用的是一个平坦通配（`artifacts/*`），所以资产清单不必再列一遍 —— 但
    这一点必须是**真的**，否则上面的断言管不住「传上去又被丢掉」这一半。
    """
    release = yaml.safe_load(WORKFLOW.read_text(encoding="utf-8"))["jobs"]["release"]
    steps = [s for s in release["steps"] if "action-gh-release" in str(s.get("uses", ""))]
    assert len(steps) == 1, f"release job 里 action-gh-release 步骤不是恰好一条：{steps}"
    files = steps[0]["with"]["files"]
    for name in (OUT_NAME, f"{OUT_NAME}.zsync"):
        assert fnmatch.fnmatch(f"artifacts/{name}", files), (
            f"release 步骤的 files={files!r} 不会带上 {name} —— 上传了也不会发布"
        )


def test_the_expected_update_info_shape_matches_the_spec_example():
    """本文件自己那条期望串的形态，对着规范里的例子核一遍（免得期望值本身写错了）。

    AppImageSpec draft.md#github-releases 的例子是
    `gh-releases-zsync|probono|AppImages|latest|Subsurface-*x86_64.AppImage.zsync`。
    """
    example = "gh-releases-zsync|probono|AppImages|latest|Subsurface-*x86_64.AppImage.zsync"
    fields = example.split("|")
    ours = EXPECTED_UPDATE_INFO.split("|")

    assert len(ours) == len(fields) == 5, f"字段数不一致：{ours} vs {fields}"
    assert ours[0] == fields[0] == "gh-releases-zsync"
    assert ours[3] == fields[3] == "latest"
    assert ours[4].endswith(".AppImage.zsync"), ours[4]
    assert "*" in ours[4], "规范允许 `*` 通配文件名；少了它更新信息就得随版本号改写"
