"use strict";
/**
 * build-vendor.js — 生成 renderer 需要的本地 vendor 文件（G26 禁 CDN，G132 语言子集）。
 *
 * 产物（提交入库，renderer 零 npm 运行时依赖）：
 *   vendor/marked.min.js            — marked UMD 构建
 *   vendor/dompurify.min.js         — DOMPurify UMD 构建
 *   vendor/highlight.custom.js      — highlight.js 核心 + ~20 常用语言子集（mini CJS loader 包装）
 *   vendor/highlight.github-dark.css— 代码高亮主题（本地 CSS）
 *   vendor/monaco/vs/**             — monaco-editor min/vs（rant 09:17:45 提示词编辑器；
 *                                     排除 language/ 与 assets/：仅用 markdown，无语言 worker，
 *                                     file:// worker 由 no-op getWorkerUrl 兜底 → 体积 24M → ~6.7M）
 *
 * 重新生成：cd emrg/gui && node scripts/build-vendor.js（需先 npm install）
 */

const fs = require("fs");
const path = require("path");

const GUI = path.join(__dirname, "..");
const VENDOR = path.join(GUI, "vendor");
const NM = path.join(GUI, "node_modules");

// G132：常用语言子集（全量 190+ 增包 ~1MB；未注册语言降级纯文本）
const SUBSET = [
  "javascript", "typescript", "python", "bash", "shell",
  "json", "yaml", "markdown", "html", "css",
  "go", "rust", "java", "c", "cpp", "sql", "diff", "xml", "ini", "dockerfile",
];

fs.mkdirSync(VENDOR, { recursive: true });

// 1. marked（UMD）
fs.copyFileSync(path.join(NM, "marked", "marked.min.js"), path.join(VENDOR, "marked.min.js"));

// 2. dompurify（UMD）
fs.copyFileSync(path.join(NM, "dompurify", "dist", "purify.min.js"), path.join(VENDOR, "dompurify.min.js"));

// 3. highlight.js 子集
const core = fs.readFileSync(path.join(NM, "highlight.js", "lib", "core.js"), "utf8");
let mods = `modules['core'] = function(module, exports, require) { ${core} };`;
const loaded = [];
for (const lang of SUBSET) {
  const p = path.join(NM, "highlight.js", "lib", "languages", `${lang}.js`);
  if (!fs.existsSync(p)) { console.warn(`[vendor] skip missing lang: ${lang}`); continue; }
  const src = fs.readFileSync(p, "utf8");
  mods += `\nmodules['lang/${lang}'] = function(module, exports, require) { ${src} };`;
  loaded.push(lang);
}
const registers = loaded.map((l) => `  hljs.registerLanguage('${l}', load('lang/${l}'));`).join("\n");
const bundle = `/* generated by scripts/build-vendor.js — highlight.js subset (G132) — do not edit */\n(function (global) {
  var modules = {};
  var cache = {};
  function load(id) {
    if (cache[id]) return cache[id].exports;
    var m = { exports: {} };
    cache[id] = m;
    modules[id](m, m.exports, load);
    return m.exports;
  }
${mods}

  var hljs = load('core');
${registers}
  global.hljs = hljs;
})(typeof window !== 'undefined' ? window : this);
`;
fs.writeFileSync(path.join(VENDOR, "highlight.custom.js"), bundle);

// 4. 主题 CSS
fs.copyFileSync(
  path.join(NM, "highlight.js", "styles", "github-dark.css"),
  path.join(VENDOR, "highlight.github-dark.css")
);

// 5. Monaco Editor（rant 2026-08-15T09:17:45/09:20:12 方案 A）：
//    拷 min/vs（排除 language/ 语言服务与 assets/ 独立 worker —— markdown 不需要）
function copyDir(src, dst) {
  fs.mkdirSync(dst, { recursive: true });
  for (const ent of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, ent.name);
    const d = path.join(dst, ent.name);
    if (ent.isDirectory()) copyDir(s, d);
    else fs.copyFileSync(s, d);
  }
}
const MONACO_SRC = path.join(NM, "monaco-editor", "min", "vs");
const MONACO_DST = path.join(VENDOR, "monaco", "vs");
fs.rmSync(MONACO_DST, { recursive: true, force: true });
copyDir(MONACO_SRC, MONACO_DST);
for (const drop of ["language", "assets"]) {
  fs.rmSync(path.join(MONACO_DST, drop), { recursive: true, force: true });
}
const monoMain = path.join(MONACO_DST, "editor", "editor.main.js");
if (!fs.existsSync(monoMain)) throw new Error("[vendor] monaco editor.main.js missing — run `npm install` first");
console.log("[vendor] monaco vendored:", MONACO_DST, `(${(fs.readdirSync(MONACO_DST, { recursive: true }).length)} files)`);

console.log("[vendor] built:", fs.readdirSync(VENDOR).sort().join(", "));
console.log(`[vendor] highlight langs: ${loaded.length} (${loaded.join("/")})`);
