#!/usr/bin/env bash
# AppImage 可更新化（rant 2026-09-30T11:42:41 要求 2 —— 官方目录的自动检查第二条：
# "The AppImage contains no update information, so users cannot update it with
#  AppImageUpdate or similar tools"）。
#
# 要达成两件事，缺一不可：
#   ① AppImage **内嵌**更新信息（runtime 的 `.upd_info`）；
#   ② AppImage **旁边**有同名 `.zsync`，且它是**在产物字节冻结之后**生成的。
#
# 为什么必须重新封装，而不是「改个配置开关」：
#   electron-builder 用自己的更新方案，上游文档的原话是「AppImages generated by
#   electron-builder cannot be updated using the usual tools」；`app-builder-lib` 的
#   AppImageTarget 传给 `app-builder appimage` 的参数里也没有任何 update-info 项。
#   上游对 electron-builder 给的路子是**唯一**的那条：用 AppImage 自己的
#   `--appimage-extract` 解成 AppDir，再用 `appimagetool -u` 重新封装。
#
# 顺序由工具自身保证，不由本脚本的语句顺序「声明」：
#   `appimagetool --help` 里 `-u` 的说明是
#       "Embed update information STRING; if zsyncmake is installed, generate zsync file"
#   —— 内嵌与 `.zsync` 生成是同一次封装的两个产物，所以 `.zsync` 必然对应最终的字节。
#   这也正是为什么本脚本最后**断言 `.zsync` 存在**：一条被静默跳过的步骤会以
#   「AppImage 在、`.zsync` 不在」收场，那正是要修的那条告警本身。
#
# 用法：
#   bash packaging/make-appimage-updatable.sh <源.AppImage> <输出目录> <产物名>
# 例：
#   bash packaging/make-appimage-updatable.sh emrg/gui/dist/EMRG-0.3.9.AppImage \
#        dist/artifacts EMRG-0.3.9-x86_64.AppImage
#
# 宿主侧对等物（本地想自己跑一次 Linux 构建时）：
#   sudo apt-get install -y zsync squashfs-tools
#   curl -fsSL -o /usr/local/bin/appimagetool \
#     "https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-$(uname -m).AppImage"
#   sudo chmod +x /usr/local/bin/appimagetool
set -euo pipefail

SRC="${1:?用法: make-appimage-updatable.sh <源.AppImage> <输出目录> <产物名>}"
OUT_DIR="${2:?输出目录未给}"
OUT_NAME="${3:?产物名未给}"

[ -f "$SRC" ] || { echo "!! 源 AppImage 不存在：$SRC" >&2; exit 1; }
mkdir -p "$OUT_DIR"

# 更新信息串的 **owner|repo** 取自本仓库自身（`GITHUB_REPOSITORY` 由 Actions 注入），
# 不写死 —— fork 出来的实例发布的 `.zsync` 在它自己的 release 上，写死就会指回上游。
# 形态是 AppImageSpec 规定的 `gh-releases-zsync|owner|repo|tag|filename`：
#   https://github.com/AppImage/AppImageSpec/blob/master/draft.md#github-releases
# tag 用 `latest`（本项目的 release 一律发布为 Latest，不是 draft / prerelease），
# filename 里的 `*` 是规范允许的通配，版本号因此不必出现在更新信息里。
REPO_SLUG="${GITHUB_REPOSITORY:-}"
if [ -z "$REPO_SLUG" ] || [ "${REPO_SLUG%%/*}" = "$REPO_SLUG" ]; then
  echo "!! GITHUB_REPOSITORY 未设置或不是 owner/repo 形态（拿到 '${REPO_SLUG}'）——" >&2
  echo "   更新信息串必须指向 .zsync 真正所在的 release，猜一个 owner/repo 会让用户的" >&2
  echo "   更新指向别人的仓库。在 CI 里它由 Actions 注入；本地跑请显式导出它。" >&2
  exit 1
fi
OWNER="${REPO_SLUG%%/*}"
REPO_NAME="${REPO_SLUG#*/}"
# 架构可由环境显式给出（测试与交叉构建），否则取宿主架构 —— 它同时决定产物名里的
# 那一段与更新信息串里 `.zsync` 的通配形态，两处必须是同一个值。
ARCH="${ARCH:-$(uname -m)}"
UPDATE_INFO="gh-releases-zsync|${OWNER}|${REPO_NAME}|latest|EMRG-*-${ARCH}.AppImage.zsync"

# 工具缺席是**失败**，不是降级：这一步的主语就是「内嵌 + `.zsync`」，跳过它等于把
# 告警原样留着，却让流水线绿着通过（本仓库对「步骤缺产物仍报成功」的既定态度，
# 见 tests/test_a_step_without_its_product_refuses.py）。
for tool in appimagetool zsyncmake mksquashfs; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "::error::${tool} 不在 PATH 上 —— AppImage 的更新信息与 .zsync 由它产生，" >&2
    echo "   跳过这一步就等于发布一个 AppImageUpdate 读不懂的 AppImage。" >&2
    echo "   缺 zsyncmake/mksquashfs：apt-get install -y zsync squashfs-tools" >&2
    echo "   缺 appimagetool：https://github.com/AppImage/appimagetool/releases/tag/continuous" >&2
    exit 1
  fi
done

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# 1. 解成 AppDir。用 AppImage 自己的 `--appimage-extract`（不依赖 FUSE 挂载），
#    产物落在当前工作目录的 squashfs-root/。
cp "$SRC" "$WORK/in.AppImage"
chmod +x "$WORK/in.AppImage"
( cd "$WORK" && APPIMAGE_EXTRACT_AND_RUN=1 ./in.AppImage --appimage-extract >/dev/null )
APPDIR="$WORK/squashfs-root"
[ -d "$APPDIR" ] || {
  echo "!! --appimage-extract 没有产出 AppDir（$APPDIR 不存在）——源文件不是可自解的" >&2
  echo "   type-2 AppImage？" >&2
  exit 1
}

# 2. 重新封装：`-u` 同时内嵌更新信息并在 zsyncmake 在场时生成 `.zsync`。
#    `-n`（--no-appstream）是刻意的：本步骤的主语是**更新信息**，而 electron-builder
#    的 AppImage 不提供 AppStream 元数据；让 AppStream 校验决定这一步的成败，会让
#    「更新信息对不对」被一个不相干的检查掩盖。
rm -f "$OUT_DIR/$OUT_NAME" "$OUT_DIR/$OUT_NAME.zsync"
( cd "$OUT_DIR" && ARCH="$ARCH" APPIMAGE_EXTRACT_AND_RUN=1 \
    appimagetool -n -u "$UPDATE_INFO" "$APPDIR" "$OUT_NAME" )

# 3. 断言两件产物都在，且 `.zsync` 说的是**同一个**文件名。
[ -s "$OUT_DIR/$OUT_NAME" ] || { echo "!! appimagetool 没有产出 $OUT_DIR/$OUT_NAME" >&2; exit 1; }
[ -s "$OUT_DIR/$OUT_NAME.zsync" ] || {
  echo "::error::appimagetool 内嵌了更新信息，但没有生成 $OUT_NAME.zsync —— zsyncmake" >&2
  echo "   虽然在场却没被用上，或 --updateinformation 没生效。缺它用户仍无法更新（这正是" >&2
  echo "  appimage.github.io 检查点名的那一条）。" >&2
  exit 1
}
if ! grep -qF "$OUT_NAME" "$OUT_DIR/$OUT_NAME.zsync"; then
  echo "!! $OUT_NAME.zsync 里没有提到 $OUT_NAME —— .zsync 与它描述的文件不是同一个" >&2
  exit 1
fi

echo "==> AppImage update information embedded: $OUT_NAME"
echo "    update information: $UPDATE_INFO"
echo "    zsync: $(basename "$OUT_DIR/$OUT_NAME.zsync") ($(wc -c <"$OUT_DIR/$OUT_NAME.zsync" | tr -d ' ') bytes)"
